/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Bookmark = IDL.Record({
  'filePath' : IDL.Text,
  'lineNumber' : IDL.Int,
  'annotation' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const CodeSnippet = IDL.Record({
  'code' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'language' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PipelineRunStatus = IDL.Variant({
  'pending' : IDL.Null,
  'failed' : IDL.Null,
  'running' : IDL.Null,
  'passed' : IDL.Null,
});
export const PipelineStageStatus = IDL.Variant({
  'pending' : IDL.Null,
  'failed' : IDL.Null,
  'running' : IDL.Null,
  'passed' : IDL.Null,
});
export const PipelineStage = IDL.Record({
  'status' : PipelineStageStatus,
  'startedAt' : IDL.Opt(IDL.Int),
  'duration' : IDL.Opt(IDL.Nat),
  'logs' : IDL.Text,
  'name' : IDL.Text,
});
export const PipelineRun = IDL.Record({
  'id' : IDL.Text,
  'stages' : IDL.Vec(PipelineStage),
  'status' : PipelineRunStatus,
  'branch' : IDL.Text,
  'createdAt' : IDL.Int,
  'triggeredBy' : IDL.Text,
  'projectId' : IDL.Text,
  'commitHash' : IDL.Text,
});
export const CodeFile = IDL.Record({
  'content' : IDL.Text,
  'name' : IDL.Text,
  'path' : IDL.Text,
  'lastModified' : IDL.Int,
  'language' : IDL.Text,
});
export const ProjectMetadata = IDL.Record({
  'projectName' : IDL.Text,
  'projectDescription' : IDL.Text,
  'lastOpened' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'preferredLanguage' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarColor' : IDL.Text,
});
export const DeploymentStatus = IDL.Variant({
  'success' : IDL.Null,
  'failed' : IDL.Null,
});
export const DeploymentRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : DeploymentStatus,
  'deployedAt' : IDL.Int,
  'version' : IDL.Text,
  'projectId' : IDL.Text,
  'environment' : IDL.Text,
  'pipelineRunId' : IDL.Text,
});
export const UserPresence = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'avatarColor' : IDL.Text,
  'lastHeartbeat' : IDL.Int,
});
export const CollabEventKind = IDL.Variant({
  'join' : IDL.Null,
  'leave' : IDL.Null,
});
export const CollabEvent = IDL.Record({
  'principal' : IDL.Principal,
  'kind' : CollabEventKind,
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Text,
});
export const Session = IDL.Record({
  'id' : IDL.Text,
  'participants' : IDL.Vec(IDL.Principal),
  'createdAt' : IDL.Int,
});
export const SessionResult = IDL.Variant({ 'ok' : Session, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addBookmark' : IDL.Func([Bookmark], [], []),
  'addCodeSnippet' : IDL.Func([CodeSnippet], [], []),
  'addToSessionHistory' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearSessionHistory' : IDL.Func([], [], []),
  'completePipelineRun' : IDL.Func([IDL.Text, PipelineRunStatus], [], []),
  'createPipelineRun' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [PipelineRun],
      [],
    ),
  'deleteBookmark' : IDL.Func([IDL.Int], [], []),
  'deleteFile' : IDL.Func([IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'deleteSnippet' : IDL.Func([IDL.Text], [], []),
  'getAllBookmarks' : IDL.Func([], [IDL.Vec(Bookmark)], ['query']),
  'getAllFiles' : IDL.Func([], [IDL.Vec(CodeFile)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(ProjectMetadata)], ['query']),
  'getAllSnippets' : IDL.Func([], [IDL.Vec(CodeSnippet)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCodeSnippet' : IDL.Func([IDL.Text], [IDL.Opt(CodeSnippet)], ['query']),
  'getDeploymentHistory' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(DeploymentRecord)],
      ['query'],
    ),
  'getEditorSettings' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getFile' : IDL.Func([IDL.Text], [IDL.Opt(CodeFile)], ['query']),
  'getOnlineUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserPresence)], ['query']),
  'getPipelineRunDetail' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PipelineRun)],
      ['query'],
    ),
  'getPipelineRuns' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(PipelineRun)],
      ['query'],
    ),
  'getProject' : IDL.Func([IDL.Text], [IDL.Opt(ProjectMetadata)], ['query']),
  'getScratchPad' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getSessionEvents' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(CollabEvent)],
      ['query'],
    ),
  'getSessionHistory' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinSession' : IDL.Func([IDL.Text], [SessionResult], []),
  'leaveSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'recordDeployment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [DeploymentRecord],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveEditorSettings' : IDL.Func([IDL.Text], [], []),
  'saveFile' : IDL.Func([CodeFile], [], []),
  'saveProject' : IDL.Func([ProjectMetadata], [], []),
  'saveScratchPad' : IDL.Func([IDL.Text], [], []),
  'saveUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePipelineStage' : IDL.Func(
      [IDL.Text, IDL.Text, PipelineStageStatus, IDL.Opt(IDL.Nat), IDL.Text],
      [],
      [],
    ),
  'updatePresenceHeartbeat' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Bookmark = IDL.Record({
    'filePath' : IDL.Text,
    'lineNumber' : IDL.Int,
    'annotation' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const CodeSnippet = IDL.Record({
    'code' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'language' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PipelineRunStatus = IDL.Variant({
    'pending' : IDL.Null,
    'failed' : IDL.Null,
    'running' : IDL.Null,
    'passed' : IDL.Null,
  });
  const PipelineStageStatus = IDL.Variant({
    'pending' : IDL.Null,
    'failed' : IDL.Null,
    'running' : IDL.Null,
    'passed' : IDL.Null,
  });
  const PipelineStage = IDL.Record({
    'status' : PipelineStageStatus,
    'startedAt' : IDL.Opt(IDL.Int),
    'duration' : IDL.Opt(IDL.Nat),
    'logs' : IDL.Text,
    'name' : IDL.Text,
  });
  const PipelineRun = IDL.Record({
    'id' : IDL.Text,
    'stages' : IDL.Vec(PipelineStage),
    'status' : PipelineRunStatus,
    'branch' : IDL.Text,
    'createdAt' : IDL.Int,
    'triggeredBy' : IDL.Text,
    'projectId' : IDL.Text,
    'commitHash' : IDL.Text,
  });
  const CodeFile = IDL.Record({
    'content' : IDL.Text,
    'name' : IDL.Text,
    'path' : IDL.Text,
    'lastModified' : IDL.Int,
    'language' : IDL.Text,
  });
  const ProjectMetadata = IDL.Record({
    'projectName' : IDL.Text,
    'projectDescription' : IDL.Text,
    'lastOpened' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'preferredLanguage' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarColor' : IDL.Text,
  });
  const DeploymentStatus = IDL.Variant({
    'success' : IDL.Null,
    'failed' : IDL.Null,
  });
  const DeploymentRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : DeploymentStatus,
    'deployedAt' : IDL.Int,
    'version' : IDL.Text,
    'projectId' : IDL.Text,
    'environment' : IDL.Text,
    'pipelineRunId' : IDL.Text,
  });
  const UserPresence = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'avatarColor' : IDL.Text,
    'lastHeartbeat' : IDL.Int,
  });
  const CollabEventKind = IDL.Variant({
    'join' : IDL.Null,
    'leave' : IDL.Null,
  });
  const CollabEvent = IDL.Record({
    'principal' : IDL.Principal,
    'kind' : CollabEventKind,
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Text,
  });
  const Session = IDL.Record({
    'id' : IDL.Text,
    'participants' : IDL.Vec(IDL.Principal),
    'createdAt' : IDL.Int,
  });
  const SessionResult = IDL.Variant({ 'ok' : Session, 'err' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addBookmark' : IDL.Func([Bookmark], [], []),
    'addCodeSnippet' : IDL.Func([CodeSnippet], [], []),
    'addToSessionHistory' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearSessionHistory' : IDL.Func([], [], []),
    'completePipelineRun' : IDL.Func([IDL.Text, PipelineRunStatus], [], []),
    'createPipelineRun' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [PipelineRun],
        [],
      ),
    'deleteBookmark' : IDL.Func([IDL.Int], [], []),
    'deleteFile' : IDL.Func([IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'deleteSnippet' : IDL.Func([IDL.Text], [], []),
    'getAllBookmarks' : IDL.Func([], [IDL.Vec(Bookmark)], ['query']),
    'getAllFiles' : IDL.Func([], [IDL.Vec(CodeFile)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(ProjectMetadata)], ['query']),
    'getAllSnippets' : IDL.Func([], [IDL.Vec(CodeSnippet)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCodeSnippet' : IDL.Func([IDL.Text], [IDL.Opt(CodeSnippet)], ['query']),
    'getDeploymentHistory' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(DeploymentRecord)],
        ['query'],
      ),
    'getEditorSettings' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getFile' : IDL.Func([IDL.Text], [IDL.Opt(CodeFile)], ['query']),
    'getOnlineUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserPresence)], ['query']),
    'getPipelineRunDetail' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PipelineRun)],
        ['query'],
      ),
    'getPipelineRuns' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(PipelineRun)],
        ['query'],
      ),
    'getProject' : IDL.Func([IDL.Text], [IDL.Opt(ProjectMetadata)], ['query']),
    'getScratchPad' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getSessionEvents' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(CollabEvent)],
        ['query'],
      ),
    'getSessionHistory' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinSession' : IDL.Func([IDL.Text], [SessionResult], []),
    'leaveSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'recordDeployment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [DeploymentRecord],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveEditorSettings' : IDL.Func([IDL.Text], [], []),
    'saveFile' : IDL.Func([CodeFile], [], []),
    'saveProject' : IDL.Func([ProjectMetadata], [], []),
    'saveScratchPad' : IDL.Func([IDL.Text], [], []),
    'saveUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePipelineStage' : IDL.Func(
        [IDL.Text, IDL.Text, PipelineStageStatus, IDL.Opt(IDL.Nat), IDL.Text],
        [],
        [],
      ),
    'updatePresenceHeartbeat' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };